suits = {"c": ["c", "club", "clbu", "clib", 
               "ckub", "clu", "cllub", "vlub", 
               "ciub", "xlub", "cpub", "cluh", 
               "cliv", "clun", "clubb", "clubs", 
               "clbus", "clubz", "clusb", "clb", 
               "cuub",
               ],
         "d": ["d", "diamond", "diamod", "diamomd", 
               "diamons", "diomond", "daimond", "diamonds", 
               "diaminds", "diamon", "diamobd", "diamojd", 
               "dimond", "diomand", "diamonf", "diamnond", 
               "diamondd", "diamomds", "diamknd", "diamnod", 
               "diampnd",
               ],
         "h": ["h", "heart", "heary", "hearrt", 
               "hear", "hearts", "heats", "hert", 
               "hearts", "hearr", "heartr", "heartt", 
               "hert", "hearst", "hearty", "hearrts", 
               "heartsa", "harts", "hearat", "hearth", 
               "heartsy",
               ],
         "s": ["s", "spade", "spad", "spae", 
               "spadde", "spaee", "spades", "spadds", 
               "spadse", "spadess", "spadesa", "spadex", 
               "spadec", "psade", "spdaes", "soade", 
               "spaed", "spadea", "spadse", "spadew", 
               "soades",
               ],
         }

